* Software-based On-line Energy Estimation for SensorNodes
Paper original que describe el funcionamiento en =contiki-os=. Es posible que la implementación en =contiki-ng= sea diferente.

** Funcionamiento
Cuando un componente (radio, sensor, led) es encendido, energest almacena un /timestamp/(=rtimer ticks=). En el instante en el que se apaga el componente, se produce un nuevo /timestamp/ y se calcula un delta y agregado a un total que indica cuanto tiempo ha permanecido encendido dicho módulo. 
Energest mantiene una tabla con una lista de los componentes y el tiempo durante el cual han permanecido encendidos.

El consumo de un módulo es estimado ante un cambio de estado, en el caso de la CPU cuando pasa de modo normal a modo de ahorro de energía.

El registro de tiempo se realiza mediante /on chip timers/ los cuales (al menos para =MSP430=) permanecen activos durante el modo de bajo consumo.

** Consideraciones especiales
+ Battery Lifetime Estimation :: No es posible traducir el consumo promedio en tiempo de vida de un mote alimentado por batería pues las baterías no son lineales.
+ Elementos no lineales :: Ciertos componentes del HW son no lineales, de tal manera que el consumo no se puede calcular como la suma de los consumos individuales de cada componente.

* Energest rontiki-ng
https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-Energest
** Tipos 
Existen al menos cinco tipos predefinidos que reconocen todas las plataformas. 
| ENERGEST_TYPE_CPU      | Tiempo de actividad de la CPU |
| ENERGEST_TYPE_LPM      | Tiempo de Low Power Mode      |
| ENERGEST_TYPE_DEEP_LPM | Tiempo de Deep Low Power Mode |
| ENERGEST_TYPE_TRANSMIT | Tiempo de transmisión         |
| ENERGEST_TYPE_LISTEN   | Tiempo de recepción           |

Para leer cualquiera de estos, se puede utilizar la función =energest_type_time(<tipo>)=. Ej:

#+begin_src c
  energest_flush();
  unsigned long last_time = ENERGEST_GET_TOTAL_TIME();
  unsigned long last_cpu = energest_type_time(ENERGEST_TYPE_CPU);
  unsigned long last_lpm = energest_type_time(ENERGEST_TYPE_LPM);
  unsigned long curr_tx = energest_type_time(ENERGEST_TYPE_TRANSMIT);
  unsigned long last_deep_lpm = energest_type_time(ENERGEST_TYPE_DEEP_LPM);
  unsigned long last_rx = energest_type_time(ENERGEST_TYPE_LISTEN);
#+end_src

No en todos los CPU funcionan en LPM y en Deep LPM. 

Para el CC2538 (openmote) se lee lo siguiente en el datasheet:
| Active-Mode RX (CPUIdle)                                                         | 20 mA  |
| Active-Mode TX at 0 dBm(CPUIdle)                                                 | 24 mA  |
| PowerMode1 (4-μs Wake-Up,32-KBRAMRetention,Full RegisterRetention)               | 0.6 mA |
| PowerMode2 (SleepTimerRunning,16-KBRAMRetention,ConfigurationRegisterRetention)  | 1.3 uA |
| PowerMode3 (ExternalInterrupts,16-KBRAMRetention,ConfigurationRegisterRetention) | 0.4 uA |

FIXME: que estos modos existan, no significa que se encuentren implementados en contiki-ng.

FIXME: Es posible también que una plataforma defina nuevos tipos para energest, por ejemplo para el sensor de temperatura,led, etc.
** Definir tipos nuevos
Debe ser posible (no probado) hacer un perfilaje energético de una función en una aplicación.
Esto puede ser útil para, por ejemplo, calcular qué tanta energía utiliza el CPU en realizar una tarea (enviar un mensaje o una serie de mensajes).

* Low Power Mode - LPM

** Intro

Contiki define tres tipos de modos de ahorro de energía. Estos son ordenados del modo de menor al mayor ahorro: PM0, PM1 y PM2

** Heurística para poner o no al CPU en /low power mode/

Cuando el planificador determina que todos los eventos han sido atendidos, llama a =lpm_enter(void)=, la cual decide en qué modo LPM 0, 1 o 2 pone al procesador.

El modo de ahorro es elegido en función de los siguientes criterios:
+ Esta apagado el RF?
+ Los periféricos registrados permiten PM1+?
+ Se disparará una interrupción de sleep timer?
 
Si la respuesta a cualquiera es no, el CPU pasa a PM0 y se despertará ante cualquier interrupción.

Caso contrario pasa a PM1 o PM2 según la duración prevista del sueño.

** PM1+
En modo PM1 o PM2 la CPU cambiar la frecuencia de trabajo a 16MHz. Además cómo no tiene timers, el proceso es ininterrumpible y tiene una duración predeterminada.

Notar que mientras en PM0 la radio puede estar encendida, en PM1+ esto no es posible.

** lpm.c - Comentado


En este apartado, intento explicar el funcionamiento del modo de ahorro de energía, así como los posibles mecanismos de bloqueo.

*** Parámetros generales
Según se ve en el archivo fuente =arch/cpu/cc2538/lpm.c=

 En primer lugar se revisa el flag =LPM_CONF_ENABLE=:
#+begin_src c
#if LPM_CONF_ENABLE != 0
#+end_src

Luego se definen intervalos de duración de los modos PM1+, en términos de ticks de rtimer. Según el comentario del código, un tick dura alrededor de 30.5 usec.
La lógica es que si la duración del período libre de interrupciones es menor a los thresholds a continuación definidos, no entrar en PM+1. Recordar que existe un período de transición entre los modos, por lo cual, no tiene sentido caer a PM1+ si se debe despertar poco tiempo después. 
 #+begin_src c
/*---------------------------------------------------------------------------*/
/*
 * Deep Sleep thresholds in rtimer ticks (~30.5 usec)
 *
 * If Deep Sleep duration < DEEP_SLEEP_PM1_THRESHOLD, simply enter PM0
 * If duration < DEEP_SLEEP_PM2_THRESHOLD drop to PM1
 * else PM2.
 */
#define DEEP_SLEEP_PM1_THRESHOLD    10
#define DEEP_SLEEP_PM2_THRESHOLD    100
 #+end_src
 
El siguiente bloque declara 3 estructuras rtimer en las cuales se guardan estadísticas que indican cuanto tiempo pasó el cpu en cada modo de ahorro de energía. Hasta donde alcanzo a comprender, no veo en qué momento se utilizan estas estadísticas.
 
Además define macros para iniciar y actualizar las estructuras. En el comentario, se indica que estas estructuras son útiles para debug.
 

#+begin_src c
  #if LPM_CONF_STATS
  rtimer_clock_t lpm_stats[3];

  #define LPM_STATS_INIT()                                                       \
    do {                                                                         \
      memset(lpm_stats, 0, sizeof(lpm_stats));                                   \
    } while (0)
  #define LPM_STATS_ADD(pm, val)                                                 \
    do {                                                                         \
      lpm_stats[pm] += val;                                                      \
    } while (0)
  #else
  #define LPM_STATS_INIT()
  #define LPM_STATS_ADD(stat, val)
  #endif
#+end_src

 En la siguiente variable se guarda el máximo PM permitido.
#+begin_src c
/*---------------------------------------------------------------------------*/
/* Stores the currently specified MAX allowed PM */
static uint8_t max_pm;
/*---------------------------------------------------------------------------*/
#+end_src

*** Consulta a periféricos
 Para poder bloquear el paso a PM1+, un módulo debe registrarse. Esto se hace en la función =lpm_register_peripheral=:
#+begin_src c
void
lpm_register_peripheral(lpm_periph_permit_pm1_func_t permit_pm1_func)
{
  int i;

  for(i = 0; i < LPM_PERIPH_PERMIT_PM1_FUNCS_MAX; i++) {
    if(periph_permit_pm1_funcs[i] == permit_pm1_func) {
      break;
    } else if(periph_permit_pm1_funcs[i] == NULL) {
      periph_permit_pm1_funcs[i] = permit_pm1_func;
      break;
    }
  }
}
#+end_src

Un ejemplo es el módulo UART, en el cual =/arch/cpu/cc2538/dev/uart.c= se define la siguiente función:
#+begin_src c
    static bool
    permit_pm1(void)
    {
      const uart_regs_t *regs;

      for(regs = &uart_regs[0]; regs < &uart_regs[UART_INSTANCE_COUNT]; regs++) {
        if((REG(regs->base + UART_FR) & UART_FR_BUSY) != 0) {
          return false;
        }
      }

      return true;
    }

  void
  uart_init(uint8_t uart)
  {
    // codigo de inicialización
    lpm_register_peripheral(permit_pm1);
    // mas código
  }

#+end_src

 Entonces: un periférico puede registrar una función que será llamada de tal forma que el módulo LPM /pida permiso/ para poder poner al mote en PM1+.
 Para el CPU =cc2538= estos módulos son:
 1) UART
 2) USB
 3) PWM
 4) PKA
 5) Crypto
 
4 y 5 son usados para conexiones seguras.

Volviendo al código de =lpm.c= la siguiente función se encarga de iterar por cada módulo y preguntar a su correspondiente función si se puede pasar a PM1+.

#+begin_src c
  static lpm_periph_permit_pm1_func_t
  periph_permit_pm1_funcs[LPM_PERIPH_PERMIT_PM1_FUNCS_MAX];
 /*---------------------------------------------------------------------------*/
 /* When changing power modes, the LPM driver will call all FPs registered with
 * this function. The peripheral's function will return true or false to permit
 *  prohibit PM1+ respectively. If at least one peripheral returns false, the
 * SoC will drop to PM0 Deep Sleep instead.
 */
  static bool
  periph_permit_pm1(void)
  {
    int i;

    for(i = 0; i < LPM_PERIPH_PERMIT_PM1_FUNCS_MAX &&
        periph_permit_pm1_funcs[i] != NULL; i++) {
      if(!periph_permit_pm1_funcs[i]()) {
        return false;
      }
    }
    return true;
  }

#+end_src

*** lpm_enter()
Finalmente todo lo anterior se utiliza en la función =lpm_enter= la cual determina el modo de ahorro de energía:

#+begin_src c
void
lpm_enter()
{
  /*
   * If either the RF or the registered peripherals are on, dropping to PM1/2
   * would equal pulling the rug (32MHz XOSC) from under their feet. Thus, we
   * only drop to PM0. PM0 is also used if max_pm==0.
   */
  if((REG(RFCORE_XREG_FSMSTAT0) & RFCORE_XREG_FSMSTAT0_FSM_FFCTRL_STATE) != 0
     || !periph_permit_pm1() || max_pm == 0) {
    enter_pm0();

    /* We reach here when the interrupt context that woke us up has returned */
    return;
  }
#+end_src

Según se puede ver, el =if= chequea tres condiciones:
1) =(REG(RFCORE_XREG_FSMSTAT0) & RFCORE_XREG_FSMSTAT0_FSM_FFCTRL_STATE)= :: El módulo de RF permite PM1+.  Más precisamente este control chequea si existen datos en la FIFO de RF.
2) =!periph_permit_pm1()= :: Todos los perifércios permiten PM1+.
3) =max_pm= :: El programador permite PM1+.

Si alguna de estas no se cumple, el mote llega hasta PM0.
